### ISSUE TITLE
Make Secret Rule Configurable in ClusterRole

### ISSUE THREAD

**Issue by gavk34** [haproxytech/helm-charts#115]
I am of the understanding that the [rule](https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/templates/clusterrole.yaml#L62)

```
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
```

is necessary for TLS termination i.e. managing secrets for Ingress resources. If a user does not wish to utilise TLS/secrets(like we do) then it makes sense not to grant such a powerful permission to the ClusterRole. I raise this because creating this ClusterRole in AZURE AKS triggered a security alert on Defender for "New high privileges role detected".
