### ISSUE TITLE
IngressClass resource not added for kubernetes-ingress

### ISSUE THREAD

**Issue by Jibux** [haproxytech/helm-charts#149]
We are using command `helm template <HELM_RELEASE_NAME> haproxytech/kubernetes-ingress --namespace <NAMESPACE> -f helm_values.yaml --version 1.22.4 --output-dir=<DIR> --include-crds` and we cannot see any `controller-ingressclass.yaml` into `<DIR>`. All other resources are present. Are we missing something?

Helm values:

```
...
controller:
  name: controller

  ingressClass: haproxy

  ingressClassResource:
    enabled: true
    default: false
...
```
