### ISSUE TITLE
enhance haproxy securityContexts for restrictive PSS compliance

### ISSUE THREAD

**Issue by joebowbeer** [haproxytech/helm-charts#150]
Installing haproxy with securityContext enabled fails to adhere to [PSS restricted profile policies](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted).

The following command reports 3 violations:

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply -r \
  <(helm template --repo https://haproxytech.github.io/helm-charts haproxy --set securityContext.enabled=true) \
  -
```

The violations are due to missing fields:

```yaml
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

`allowPrivilegeEscalation` can only be set in the container-level securityContext, but the other two can be set in the pod-level or container-level securityContext.

Proposal:

Add these to the default container-level securityContext values so that they will be added when securityContext.enabled is true.
