### ISSUE TITLE
add runAsNonRoot to templates/deployment.yaml

### ISSUE THREAD

**Issue by joawin** [haproxytech/helm-charts#157]
Hi,
to use `runAsNonRoot` in values.yaml i guess we have to add it to the templates file

`runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
`
>  securityContext:
>             runAsUser: {{ .Values.securityContext.runAsUser }}
>             runAsGroup: {{ .Values.securityContext.runAsGroup }}
>             runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
>             capabilities:
>               drop:
>                 - ALL
>               add:
>                 - NET_BIND_SERVICE

**Comment by dkorunic** [comment]
@joawin It is not clear if you are referring to `haproxy` Helm chart or `ingress-controller` Helm chart and what is the exact question. I will however try to help, let me know if I have answered what you have been asking about.

In case of  Ingress controller, we have some very specific defaults which are non-tunable and have to remain as is:

```
          {{- if .Values.controller.unprivileged }}
          securityContext:
            runAsUser:  1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            {{- if .Values.controller.enableRuntimeDefaultSeccompProfile }}
            seccompProfile:
              type: RuntimeDefault
            {{- end }}
```
Ingress controller by default runs in unprivileged mode and by default maps to UID 1000 / GID 1000 and drops all privileges.

Helm chart however does not run by default in unprivileged mode since it is not being actively managed (like with Ingress controller) and HAproxy configuration is entirely left to user, so it might be needing elevated privileges. However, we do have a security-tunable configuration in values.yaml:

```
securityContext:
  enabled: false
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE
  seccompProfile:
    type: RuntimeDefault
```

When enabling this block (`enabled: true`) these values will be activated and applied.

**Comment by joawin** [comment]
Hi,
i am referring to `haproxy`.
I have set 
```
securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE
  seccompProfile:
    type: RuntimeDefault
````

when i now run 
`helm template abc . -f values.yaml `
 runAsNonRoot is not in the output.

```
containers:
        - name: haproxy
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
```

Therefor you have to add it in `templates/deployment.yaml`

current:
```
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
```


new:
```
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
```
