### ISSUE TITLE
Ingress Service Monitor doesn't show up in Prometheus targets

### ISSUE THREAD

**Issue by Daxcor69** [haproxytech/helm-charts#160]
I have installed the community prometheus operator/stack.

I have followed the instructions:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

helm install prometheus prometheus-community/kube-prometheus-stack \
  --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \
  --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false

helm install my-ingress haproxytech/kubernetes-ingress \
  --set controller.serviceMonitor.enabled=true
```
The service Monitor crd for harproxy ingress shows up in the list.  When I go to the prometheus->target  ui  I don't see haproxy there.  I also, to be expected, don't see any metrics.

Here is the helm chart snippet
```
  serviceMonitor:
    ## Toggle the ServiceMonitor true if you have Prometheus Operator installed and configured
    enabled: true

    ## Specify the labels to add to the ServiceMonitors to be selected for target discovery
    extraLabels:
      release: mon                 ###### this is the name of the prometheus helm release ##

    endpoints:
      - port: stat
        path: /metrics
        scheme: http
        interval: 30s
```
When looking through logs I don't see any mention of a service monitor or bad target. I need some direction on where to look next fo r the issue.

Thanks
Brad

**Comment by Daxcor69** [comment]
I added --set controller.serviceMonitor.extraLabels.release: prometheus-operator   and this fixed the issue.  Maybe add this to the documentation?

**Comment by dkorunic** [comment]
@Daxcor69 By default, Helm Chart for IC uses the following selector labels:
```
    selector:
      matchLabels:
        app.kubernetes.io/name: {{ template "kubernetes-ingress.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
```

If you have set `serviceMonitorSelectorNilUsesHelmValues: false` like you mentioned, Prometheus Operator should have fetched selector labels from all ServiceMonitor resources in the same namespace and everything should have worked automatically. Since you had to set labels manually, I think there is some kind of problem with Prometheus Operator on your end...
