### ISSUE TITLE
securityContext values are set in HelmChart but not in Github

### ISSUE THREAD

**Issue by joawin** [haproxytech/helm-charts#164]
https://github.com/haproxytech/helm-charts/blob/5a8f86da465a2831cc63aa01af69f937bfa1cb31/haproxy/values.yaml#L364

Values for securityContext are not defined here 
```
securityContext: {}
#  runAsUser: 1000
#  runAsGroup: 1000
#  allowPrivilegeEscalation: true
#  runAsNonRoot: true
#  capabilities:
#    drop:
#      - ALL
#    add:
#      - NET_BIND_SERVICE
#  seccompProfile:
#    type: RuntimeDefault
```

But if i download Helm-Chart 1.17.0 values are defined

```
## Container Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  enabled: false
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE
  seccompProfile:
    type: RuntimeDefault
```
