### ISSUE TITLE
All configurable updateStrategy for daemonset

### ISSUE THREAD

**Issue by gregod-com** [haproxytech/helm-charts#186]
When deploying haproxy kubernetes ingress as `Daemonset`, the values
```yaml
controller:
[...]
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
[...]
```
are not applied, since they are not evaluated here https://github.com/haproxytech/helm-charts/blob/d83ded99ae2bd346891a77e6e7c188b5f328f54d/kubernetes-ingress/templates/controller-daemonset.yaml#L37
as they are when deploying as `Deployment`, like here
https://github.com/haproxytech/helm-charts/blob/d83ded99ae2bd346891a77e6e7c188b5f328f54d/kubernetes-ingress/templates/controller-deployment.yaml#L42

Request:
Let the user define how the `updateStrategy` block in the resulting `Daemonset` looks like by either
* introducing a new values object named `updateStrategy`
* or
* reuse the values object named `strategy`

The update strategy is supported by kubernetes, as the official docs state:
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec

This change would allow for zero downtime when running haproxy kubernetes ingress as `Daemonset` with the service being exposed as `NodePort`
