### ISSUE TITLE
DualStack Capabilities /Deployment

### ISSUE THREAD

**Issue by eifelmicha** [haproxytech/helm-charts#194]
Hello,
i noticed the chart lacks documentation / possibility of deploy to DualStack Clusters. I see quite some problems when using IPv6 annd noticced following options are missing on the Service:
- `spec.ipFamilies`
- `spec.ipFamilyPolicy`

Are there plans to add them and cover dualstack in documentation better?

**Comment by dkorunic** [comment]
Dear @eifelmicha, we would like to hear more, if possible: 1) which Chart you are referring to (there are two Helm Charts, one for bare HAProxy on K8s and another for Ingress Controller based on HAProxy) and 2) describe issues you are having with IPv4/IPv6 dual stack. I am assuming that you wanted to enable IPv6 cluster-wide, for both pods and services?

**Comment by eifelmicha** [comment]
1) Ingress Controller based on HAProxy
2)
 I run `curl -I https://fqdn/ -6` and i see nearly every second request gets `curl: (35) Recv failure: Connection reset by peer` messages, which do not appear with `-4` and also not with haproxy deployed on node on different port or with ingress controller https://github.com/jcmoraisjr/haproxy-ingress deployed. I don't see any hints in the logs from the pods and needed to switch back.

Deployed values:
```yaml
---
controller:
  name: controller
  kind: DaemonSet

  ingressClass: haproxy
  ingressClassResource:
    name: haproxy
    default: true

  dnsPolicy: ClusterFirstWithHostNet
  daemonset:
    useHostNetwork: true
    useHostPort: true
    hostPorts:
      http: 80
      https: 443
      stat: 1024

  containerPort:
    http: 80
    https: 443
    stat: 1024

  config:
    timeout-client: 3600s
    timeout-connect: 3600s
    timeout-server: 3600s
    max-connections: "10000"

  service:
    enabled: false

    tcpPorts:
      - name: gitea
        port: 22222

  extraEnvs:
    ## Set TZ env to configure timezone on controller containers
    - name: TZ
      value: "Europe/Berlin"

  serviceMonitor:
    enabled: true

    extraLabels:
      monitoring: prometheus

    endpoints:
      - port: stat
        path: /metrics
        scheme: http
        interval: 30s

```
