### ISSUE TITLE
ClusterRole missing rights on AKS

### ISSUE THREAD

**Issue by HSoulat** [haproxytech/helm-charts#196]
haproxy-ingress pod is missing at least the following rights on AKS cluster.

```
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - get
```
