### ISSUE TITLE
binding to privileged port fail

### ISSUE THREAD

**Issue by owanio1992** [haproxytech/helm-charts#219]
hello
I am using helm install 1.10.10 version ingress 
and change value 
```
controller:
  containerPort:
    http: 80
    https: 443
    stat: 1024
  unprivileged: true
  allowPrivilegeEscalation: true
  kind: DaemonSet
  daemonset:
    useHostNetwork: true
```

but will get error
```
s6-overlay-preinit: fatal: unable to chown /var/run/s6: Operation not permitted
```

and I add `CHOWN` to securityContext.capabilities.add can fix this issue
hope can update this config to helm 
thank very much

**Comment by dkorunic** [comment]
@owanio1992 There is no reason to bind to privileged ports for container. Can you explain your use-case?

**Comment by dkorunic** [comment]
Can you try with these values and report if you are still seeing any kind of error?

```
controller:
  containerPort:
    http: 80
    https: 443
    stat: 1024
  kind: DaemonSet
  daemonset:
    useHostNetwork: true
    useHostPort: true
    hostPorts:
      http: 80
      https: 443
      stat: 1024
```
