### ISSUE TITLE
No access possible in local docker desktop installation

### ISSUE THREAD

**Issue by khauser** [haproxytech/helm-charts#221]
When I deploy a nginx ingress I am able to access my application via 80 and 443. This does also work with https://haproxy-ingress.github.io/.

The haproxytech ingress doesn't seem to work the same way and I have no access to my application.

**Install ingress**:

haproxy-ingress.yaml
```
controller:
  replicaCount: 1
defaultBackend:
  enabled: false
```

```
helm upgrade ingress-controller haproxytech/kubernetes-ingress \
    --install \
    --force \
    --wait \
    --namespace ingress-controller \
    --create-namespace \
    --version 1.36.1 \
    --set controller.logging.level=debug \
    -f helm/haproxy-ingress.yaml
```

My Application Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
...
spec:
  ingressClassName: haproxy
  rules:
  - host: <my domain>
    http:
      paths:
      - backend:
          service:
            name: <my service>
            port:
              name: svc
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - <my domain>
    secretName: ingress-tls-csi
```

**Comment by dkorunic** [comment]
When you are saying this is running under Docker, I presume you are using [Kind](https://github.com/kubernetes-sigs/kind) under Docker?
In regards to tcp/80 and tcp/443, you should be able to access through `clusterIP` for your kubernetes-ingress service and it should be listening to tcp/80 and tcp/443. In case that doesn't work, problem is in your network (Docker, K8s, host) setup.

**Comment by khauser** [comment]
@dkronic Thanks for your message. Docker for Desktop on Windows comes with Kubernetes itself. I'll check with the clusterIp.

**Comment by khauser** [comment]
So okay, ClusterIP is only cluster internal. But I need access from outsite the cluster. So then it should be NortPort service.

**Comment by dkorunic** [comment]
Most likely you would like to have a LoadBalancer service, ie:

```
controller:
  kind: DaemonSet
  ingressClass: haproxy
  service:
    type: LoadBalancer
```

But it is really hard to tell at this point what are you trying to do, given the lack of information..
