### ISSUE TITLE
missing https 443 container port

### ISSUE THREAD

**Issue by Jacq** [haproxytech/helm-charts#237]
After last upgrade to chart v1.39.2 we experience issues with https services and checking the daemonset deployment we found that the https mapping is missing:
```yaml
          ports:
            - containerPort: 8080
              hostPort: 80
              name: http
              protocol: TCP
            - containerPort: 8443
              hostPort: 443
              name: quic
              protocol: UDP
            - containerPort: 1024
              hostPort: 1024
              name: stat
              protocol: TCP
```

The https port is correctly enanbled and mapped in the values.yaml but it is missing from the above list, we also checked the template generation using helm --debug locally and it is generated ok including the https map. 
Our upgrade was performed from Rancher UI so this might an issue related to Rancher and not to this helm chart, anyone is having a similar problem? 

Cheers,
Jacq
