### ISSUE TITLE
It would be interesting to be able to introduce additional metadata labels in the deployments and statefulsets

### ISSUE THREAD

**Issue by gustavoborragan** [haproxytech/helm-charts#250]
It would be interesting to be able to introduce additional metadata labels in the deployments and statefulsets.

Current deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ...
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 2.8.1
    helm.sh/chart: haproxy-1.19.2
```

With `deploymentLabels` key into values:

```yaml
deploymentLabels:
  foo: bar
  bar: foo
```

Desired deployments:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ...
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 2.8.1
    bar: foo
    foo: bar
    helm.sh/chart: haproxy-1.19.2
```
