### ISSUE TITLE
kubernetes-ingress: Make controller.podAnnotations templatable

### ISSUE THREAD

**Issue by phihos** [haproxytech/helm-charts#275]
Similar to `controller.extraVolumeMounts` `controller.podAnnotations` should be templatable when provided as string.

Use Case:

When using `controller.extraEnvFrom` the pod is not restarted when the corresponding configmap changes. According to [helm best-practices](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) we should add a checksum annotation to the pod annotations that changes whenever the content of the configmap changes.

With templatable `controller.podAnnotations` the following would be possible from a parent chart:

```yaml
# values.yaml
kubernetes-ingress:
  controller:
    extraEnvFrom:
      - configMapRef:
          name: my-env-vars
    podAnnotations: |
      env-var-checksum: {{ $.Values.customEnvVars | toYaml | sha256sum }}
  customEnvVars:
    FOO: BAR
```

``` yaml
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env-vars
data: {{ (index .Values "kubernetes-ingress").customEnvVars | toYaml | nindent 2 }}
```

**Comment by phihos** [comment]
> We don't really use anything in particular from env variables so that this would apply, nor anything in particular that would make sense for extraVolumeMounts and podAnnotations to be templateable.

`extraVolumeMounts` [is already templatable](https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/templates/controller-deployment.yaml#L238).

> especially for Ingress Controller services that we want to be restarted as little as possible.
True, but there are cases like that. One such case is making the frontend config snippet parametrizable. In my case for example I have HAProxy IC on-prem (big nodes, high ulimits) and cloud (small nodes, low ulimits). I would like to set a different maxconn value for the https frontend but leave the rest of the config the same. Assuming the config from above exists I can do something like this from a parent helm chart:

```yaml
# values-common.yaml
kubernetes-ingress:
  controller:
    extraEnvFrom:
      - configMapRef:
          name: my-env-vars
    podAnnotations: |
      env-var-checksum: {{ $.Values.customEnvVars | toYaml | sha256sum }}
    config:
      frontend-config-snippet: |
        # ...
        .if streq("${.SECTION}",https)
          maxconn "$MAXCONN_FRONTEND_HTTPS"
        .endif
        # ...
```

```yaml
# values-on-prem.yaml
kubernetes-ingress:
  customEnvVars:
    MAXCONN_FRONTEND_HTTPS: 100000
```

```yaml
# values-on-cloud.yaml
kubernetes-ingress:
  customEnvVars:
    MAXCONN_FRONTEND_HTTPS: 50000
```

When the env var `FRONTEND_MAXCONN` changes I would like this to be effective as fast as possible. Does the use-case make more sense now?

**Comment by dkorunic** [comment]
@phihos I don't really mind adding this, but I wanted to point out (my apologies again for nitpicking) that in KIC, global maxconn is already auto-calculated from either host RAM (where there are no Cgroups v1/v2 in effect) or from hard limits (where there are present Cgroups v1/v2 limits), taking into account SSL cache, buffers and Golang KIC usage. There is of course no harm in setting individual frontend limits if that is exactly what you want to do.

**Comment by phihos** [comment]
> I don't really mind adding this

Thank you. I will open another PR soon.

> my apologies again for nitpicking
No need. I am always grateful when people offer me alternative solutions.

> global maxconn is already auto-calculated from either host RAM [...]
Yes I know, but in my case it was actually too low, because it was equally distributed between http, https, stats and healthz. This does not make much sense if https is heavily utilized and the rest not really. 

But there are more use-cases for parametrizing the frontend-config with env vars. If your organization has a security team, which is interested in which TLS cipher suites are used (and only that) you can do the following:

```yaml
# values-common.yaml
kubernetes-ingress:
  controller:
    extraEnvFrom:
      - configMapRef:
          name: my-env-vars
    podAnnotations: |
      env-var-checksum: {{ $.Values.customEnvVars | toYaml | sha256sum }}
    config:
      global-config-snippet: |
        ssl-default-bind-ciphers "${CIPHERS_DEFAULT_TLS_12}"
        ssl-default-bind-ciphersuites "${CIPHERS_DEFAULT_TLS_13}"
      frontend-config-snippet: |
        # ...
        .if streq("${.SECTION}",https)
          bind 0.0.0.0:8444 name v4 ssl accept-proxy ciphers "${CIPHERS_PROXY_PROTOCOL_TLS_12}" ciphersuites  "${CIPHERS_PROXY_PROTOCOL_TLS_13}"
        .elif streq("${.SECTION}",http)
          bind 0.0.0.0:8081 name v4 accept-proxy
        .endif
        # ...
```
```yaml
# values-tls.yaml
# Dear security team you may review and edit the lines below.
kubernetes-ingress:
  customEnvVars:
    CIPHERS_DEFAULT_TLS_12: "..."
    CIPHERS_DEFAULT_TLS_13: "..."
    CIPHERS_PROXY_PROTOCOL_TLS_12: "..."
    CIPHERS_PROXY_PROTOCOL_TLS_13: "..."
```

This way you can link just the file at the bottom in  the relevant docs and nobody has to deal with implementation details if they don't want to.
