### ISSUE TITLE
kubernetes-ingress: Make controller.config templatable

### ISSUE THREAD

**Issue by phihos** [haproxytech/helm-charts#278]
Hi,

I thought about what @dkorunic said in [this comment](https://github.com/haproxytech/helm-charts/issues/275#issuecomment-2556957738). Especially

> We don't really want pod restarts either, whatever helm mentions as best practice, it's not necessarily applicable to everything, especially for Ingress Controller services that we want to be restarted as little as possible.

The use-case in #275 was to make global, frontend or backend config snippets parametrizable like this:

```yaml
# values-common.yaml
kubernetes-ingress:
  controller:
    extraEnvFrom:
      - configMapRef:
          name: my-env-vars
    podAnnotations: |
      env-var-checksum: {{ $.Values.customEnvVars | toYaml | sha256sum }}
    config:
      frontend-config-snippet: |
        # ...
        .if streq("${.SECTION}",https)
          maxconn "$MAXCONN_FRONTEND_HTTPS"
        .endif
        # ...
  customEnvVars:
    # default value to be overridden
    MAXCONN_FRONTEND_HTTPS: 30000
```

As @dkorunic pointed out this will cause pods to restart which we want to avoid. Instead we could make `controller.config` templatable and achieve the same without restart:

```yaml
# values-common.yaml
kubernetes-ingress:
  controller:
    config: |
      frontend-config-snippet: |
        # ...
        .if streq("${.SECTION}",https)
          maxconn {{ .Values.customVars.maxconnFrontendHttps | required "customVars.maxconnFrontendHttps must be defined" }}
        .endif
        # ...
  customVars:
    # default value to be overridden
    maxconnFrontendHttps: 30000
```

The config is equivalent to the snippet above, but we now have additional validation preventing empty values to be inserted.
Whenever the config changes, the configmap is re-ingested by the IC and haproxy is reloaded. No restart necessary.

The same use-cases as in #275 apply here: Parametrizing config snippets so single variables can be different on different deployments, better separation of config and sets of tunables that are of interest to different teams in an organization (see [this example](https://github.com/haproxytech/helm-charts/issues/275#issuecomment-2557110722)).

This would not make #275 obsolete as  templatable podAnnotations are still needed when changing `haproxy-auxiliary-configmap` ([docs](https://www.haproxy.com/documentation/kubernetes-ingress/ingress-tutorials/auxiliary-config-file/#deploy-the-ingress-controller)) as is can be only refreshed via pod restart.
