### ISSUE TITLE
Ingress randomly changes the address from the metalib pool

### ISSUE THREAD

**Issue by olegans1972** [haproxytech/helm-charts#282]
```
[opodguyko@copula-lab-1 ~]$ sudo kubectl get ipaddresspools.metallb.io -A
NAMESPACE        NAME         AUTO ASSIGN   AVOID BUGGY IPS   ADDRESSES
infrastructure   ippool-oam   false         false             ["192.168.57.205/32","192.168.57.206/32","192.168.57.207/32","192.168.57.208/32","192.168.57.209/32"]
```

```
[opodguyko@copula-lab-1 ~]$ sudo kubectl get svc -A  | grep -i ingress
gpbm-va           haproxy-ingress-gpbm-va-kubernetes-ingress                        LoadBalancer   10.43.226.253   192.168.57.208   80:32669/TCP,443:31123/TCP,443:31123/UDP,1024:30295/TCP,6060:32013/TCP                                           15h
sbertel-va        haproxy-ingress-sbertel-va-kubernetes-ingress                     LoadBalancer   10.43.179.63    192.168.57.206   80:30619/TCP,443:31708/TCP,443:31708/UDP,1024:30638/TCP,6060:30159/TCP                                           15h
t2-va             haproxy-ingress-t2-va-kubernetes-ingress                          LoadBalancer   10.43.189.242   192.168.57.207   80:30630/TCP,443:31817/TCP,443:31817/UDP,1024:30227/TCP,6060:30727/TCP                                           14h


```
When I install ingress I set the variables like this

```
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: "haproxy-ingress-{{ k8s_resource_namespace }}"
  namespace: "{{ k8s_resource_namespace }}"
spec:
  chart: "{{ sifox_repo }}/cpaas/demo/repo-helm/haproxy-kubernetes-ingress/kubernetes-ingress-1.39.4.tgz"
  set:
  valuesContent: |-
    controller:
      image:
        repository: gitlab.sifox.ru:5000/cpaas/demo/repo-docker/kubernetes-ingress
      replicaCount: 1
      ingressClassResource:
        name: "{{ k8s_resource_namespace }}"
      extraArgs:
        - --disable-ipv6
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: "{{ va_external_vip }}"
          metallb.universe.tf/loadBalancerIPs: "{{ va_external_vip }}"
      serviceMonitor:
        enabled: true
```
where va_external_vip  one of IPs from metalib.
I'm observing strange behavior. All three ingress chaotically change IP addresses from 206 to 208:

````
[opodguyko@copula-lab-1 ~]$ sudo kubectl get ingress -n t2-va
NAME     CLASS   HOSTS   ADDRESS          PORTS   AGE
spamdb   t2-va   *       192.168.57.208   80      43h
va-rmq   t2-va   *       192.168.57.208   80      3d19h
[opodguyko@copula-lab-1 ~]$ 
[opodguyko@copula-lab-1 ~]$ sudo kubectl get ingress -n t2-va
NAME     CLASS   HOSTS   ADDRESS          PORTS   AGE
spamdb   t2-va   *       192.168.57.208   80      43h
va-rmq   t2-va   *       192.168.57.208   80      3d19h
[opodguyko@copula-lab-1 ~]$ 
[opodguyko@copula-lab-1 ~]$ sudo kubectl get ingress -n t2-va
NAME     CLASS   HOSTS   ADDRESS          PORTS   AGE
spamdb   t2-va   *       192.168.57.208   80      43h
va-rmq   t2-va   *       192.168.57.208   80      3d19h
[opodguyko@copula-lab-1 ~]$ 
[opodguyko@copula-lab-1 ~]$ 
[opodguyko@copula-lab-1 ~]$ sudo kubectl get ingress -n t2-va
NAME     CLASS   HOSTS   ADDRESS          PORTS   AGE
spamdb   t2-va   *       192.168.57.206   80      43h
va-rmq   t2-va   *       192.168.57.206   80      3d19h
[opodguyko@copula-lab-1 ~]$ sudo kubectl get ingress -n t2-va
NAME     CLASS   HOSTS   ADDRESS          PORTS   AGE
spamdb   t2-va   *       192.168.57.207   80      43h
va-rmq   t2-va   *       192.168.57.207   80      3d19h
[opodguyko@copula-lab-1 ~]$ 
````

All this happens in real time. Of course the services don't work. As soon as I remove two of the three ingress - the IP stops changing

**Comment by dkorunic** [comment]
@olegans1972 This behaviour is not related to our Helm Chart, but to [Metallb](https://metallb.io/) and this is exactly what you have asked to happen with annotation `metallb.universe.tf/allow-shared-ip`, as shown in the Metallb [documentation](https://metallb.universe.tf/usage/#ip-address-sharing). The only way this can work is if you either pick different ports to work with or use different external IPs.

**Comment by olegans1972** [comment]
In fact, everything is treated using your settings. Metallib has nothing to do with it. We use your haproxytech in three different namespaces and this option allowed all three haproxytech instances to work simultaneously and not interfere with each other

```
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: "haproxy-ingress-{{ k8s_resource_namespace }}"
  namespace: "{{ k8s_resource_namespace }}"
spec:
  chart: "{{ sifox_repo }}/cpaas/demo/repo-helm/haproxy-kubernetes-ingress/kubernetes-ingress-1.39.4.tgz"
  set:
  valuesContent: |-
    controller:
      image:
        repository: gitlab.sifox.ru:5000/cpaas/demo/repo-docker/kubernetes-ingress
      replicaCount: 1
      ingressClassResource:
        name: "{{ k8s_resource_namespace }}"
      extraArgs:
        - --disable-ipv6
        - --namespace-whitelist=t2-va
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: "{{ va_external_vip }}"
          metallb.universe.tf/loadBalancerIPs: "{{ va_external_vip }}"
      serviceMonitor:
        enabled: true
```


All you had to do was add an option to the settings of each ingress

```
- --namespace-whitelist=t2-va
```
