### ISSUE TITLE
Mounting ConfigMap prevents hot reload due to subPath option using sidecar container

### ISSUE THREAD

**Issue by timur-ND** [haproxytech/helm-charts#284]
Hello. I see that **subPath** is used in the template https://github.com/haproxytech/helm-charts/blob/haproxy-1.23.0/haproxy/templates/deployment.yaml#L152C1-L155C57 .
But **subPath** prevents re-genarating haproxy config after changing https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath . So sidecarContainers option seems useless and hot reload is not available (inside sidecar config is changed):

```
sidecarContainers:
  - name: reflex
    image: acim/go-reflex:1.17.3
    command: ["reflex", "-d", "fancy"]
    workingDir: /usr/local/etc/haproxy
    args:
      - -svr
      - "..data"
      - --
      - bash
      - -c
      - 'pkill -SIGUSR2 "haproxy|hapee-lb"'
    volumeMounts:
      - name: haproxy-config
        mountPath: /usr/local/etc/haproxy
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
```

May I ask, could you please  add **subPath** option as an optional, or should I download all templates and use my local templates? :)
```
volumeMounts:
  - name: haproxy-config
    mountPath: {{ .Values.configMount.mountPath }}
    {{- if .Values.configMount.subPath }}
    subPath: {{ .Values.configMount.subPath }}
    {{- end }}
```
Thank you

**Comment by dkorunic** [comment]
Absolutely, this makes sense and there are no downsides of having this.

**Comment by tuxillo** [comment]
@dkorunic I can take care of creating the PR, or do you have something additional in mind?

**Comment by dkorunic** [comment]
PR is fine as well, it would be gladly accepted. I would have done this earlier, but we have other things in the pipeline - my apologies.

**Comment by tuxillo** [comment]
@timur-ND are you using `shareProcessNamespace` together with go-reflex? Otherwise, how would you be able to signal a process in another container?

**Comment by timur-ND** [comment]
@tuxillo Yes, I tested with these params:
```
checksumConfigMap:
  enabled: false
shareProcessNamespace:
  enabled: true
```
Disabled checksum (to avoid restarts after deploy new config) and shareProcessNamespace
