### ISSUE TITLE
Setting port of service to different port than that of controller container not possible

### ISSUE THREAD

**Issue by skaffille** [haproxytech/helm-charts#37]
The controller-deployment.yaml declares the container ports for the ingress controller with help of the (TCP) ports defined for the service. This is the definition in the template file:

```
          {{- range .Values.controller.service.tcpPorts }}
            - name: {{ .name }}-tcp
              containerPort: {{ .port }}
              protocol: TCP
          {{- end }}
```

Shouldn't the ```containerPort``` be mapped to ```.targetPort```?

As it is now it is not possible to use a different port on the service than that of the controller.

**Comment by skaffille** [comment]
Workaround:

Define the service yourself and disable it in the helm chart, but define the ports in the values.yaml.
E.g.

values.yaml:
```
controller:
  service:
    enabled: false
    tcpPorts:
       - name: myport
         port: 4711
```
Service:
```
apiVersion: v1
kind: Service
metadata:
   name: kubernetes-ingress
   labels:
      app.kubernetes.io/name: kubernetes-ingress
spec:
  ports:
   - name: myport
     port: 9999
     targetPort: 4711
     protocol: TCP
selector:
   app.kubernetes.io/name: kubernetes-ingress
type: LoadBalancer
```
