### ISSUE TITLE
Support lifecycle additions on controller - for hooks

### ISSUE THREAD

**Issue by EFX-PXT1** [haproxytech/helm-charts#40]
Be great if the chart had support for lifecycle to add hooks to the controller.
Personal example being a preStop for graceful shutdown.

```
controller:
  lifecycle:
    # graceful shutdown
    preStop:
      exec:
        command: ["/bin/sh", "-c", "kill -USR1 $(pidof haproxy); while killall -0 haproxy; do sleep 1; done"]
```

But generally useful to support.
