### ISSUE TITLE
[kubernetes-ingress] Allow existing secret for imagePullSecret

### ISSUE THREAD

**Issue by tbnguyen1407** [haproxytech/helm-charts#53]
**Problem**

Currently registry credentials must be specified in plaintext in values.yaml

```
controller:
  imageCredentials:
    registry: ...
    username: ...
    password: ...
```

**Suggestion**

Allow specifying existing registry secret so credentials can be managed outside of values.yaml

```
controller:
  image:
    repository: ...
    tag: ...
    pullPolicy: ...
    pullSecrets: [ ... ]
```
