### ISSUE TITLE
[controller image] Building HAProxy image with Lua module(s)

### ISSUE THREAD

**Issue by mecampbellsoup** [haproxytech/helm-charts#54]
Hi guys - 

How would you suggest going about building an HAProxy image with either:

1. Lua module installable as a luarock, i.e. `luarocks install pgmoon`; or
2. Custom lua module that I wrote locally (think `COPY ./my-lua-module /src/` in a Dockerfile) or some custom GitHub repo (think `RUN git clone https://github.com/foo/some-lua-module` in Dockerfile)

In my case I have a fork of [pgmoon](https://github.com/leafo/pgmoon) that is not yet merged into the upstream that I would like to have available in my HAProxy image for some custom lua scripting.

**Comment by tbnguyen1407** [comment]
I think you can try a few options:

**(1) Build your own image, adding your binaries**

```
~ Dockerfile ~ (my-kubernetes-ingress)
FROM haproxytech/kubernetes-ingress:<tag>

## add your binaries here
```
then use in place of official image
```
~ myvalues.yaml ~
controller.image.repository: my-kubernetes-ingress:mytag
```

**(2) If your binaries are small enough (< 1MB) you can create a secret from them**
```
kubectl create secret generic mysecret --from-file=/path/to/file1 --from-file=/path/to/file2
```
then mount the secret as volume
```
~ myvalues.yaml ~
controller:
  extraVolumes:
    - name: myvolume
      secret:
        secretName: mysecret
  extraVolumeMounts:
    - name: myvolume
      mountPath: /path/to/plugins
```
**(3) If you don't want to rebuild image everytime there is an update, build a lightweight image containing only your binaries**
```
~ Dockerfile ~ (my-kubernetes-ingress-plugins)
FROM alpine

## add your binaries here (e.g. to /path/to/plugins)
```
then copy it to main container using initContainer
```
~ myvalues.yaml ~
controller:
  extraVolumes:
    - name: myvolume
      emptyDir: {}
  extraVolumeMounts:
    - name: myvolume
      mountPath: /path/to/plugins
  initContainers:
    - name: myinitcontainer
      image: my-kubernetes-ingress-plugins:mytag
      command: ["/bin/sh", "-c", "cp -pr /path/to/plugins/* /myplugins"]
      volumeMounts:
        - name: myvolume
          mountPath: /myplugins
```
