### ISSUE TITLE
[ConfigMap] global-config-snippet value not written to haproxy.cfg file

### ISSUE THREAD

**Issue by mecampbellsoup** [haproxytech/helm-charts#55]
Hi guys -

I am using the `haproxytech/kubernetes-ingress` Helm chart as a dependency in my chart.

Here are relevant values from my `values.yaml` file:

```yaml
kubernetes-ingress:
  controller:
    image:
      repository: localhost:5000/kubernetes-ingress
      tag: latest
    config:
      global-config-snippet: |
        lua-load test.lua
    logging:
      traffic:
        address: stdout
        format: raw
        facility: daemon
```
You can see the Helm template [here](https://github.com/haproxytech/helm-charts/blob/master/kubernetes-ingress/templates/controller-configmap.yaml#L33).

Here is how the resultant `ConfigMap` looks after I install my chart:

```
k8s-services git:(mc/cloud-charts) ✗ k get configmaps gatekeeper-kubernetes-ingress -o json | jq -r .data
{
  "global-config-snippet": "lua-load test.lua\n",
  "syslog-server": "address:stdout, facility:daemon, format:raw,"
}
```
So, things look _fine_ to me - however, when I check the controller image's `/etc/haproxy/haproxy.cfg` file, I don't see the above `global-config-snippet` written to this file:

```
k8s-services git:(mc/cloud-charts) ✗ k exec -it gatekeeper-kubernetes-ingress-67846778b5-gtxhj -- /bin/sh
/ # cat /etc/haproxy/haproxy.cfg | grep lua-load
```
This seems like a bug, no?
