### ISSUE TITLE
Kubernetes-ingress chart should create ingressclass object if controller.ingressClass is not null

### ISSUE THREAD

**Issue by gtrubach** [haproxytech/helm-charts#91]
The preferred way to specify ingress class is through `IngressClass` object instead of annotation now - https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class. As stated in https://github.com/haproxytech/kubernetes-ingress/issues/307 haproxy already supports this but IngressClass has to be created manually now. I tried to create below object and it indeed works.

```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy
spec:
  controller: haproxy.org/ingress-controller
```

Ideally this object should be installed with the helm chart if `controller.ingressClass` is not null. Can this be implemented in this chart?
