### ISSUE TITLE
haproxy template files daemonset.yaml and deployment.yaml do not allow to configure metadata.annotations using values

### ISSUE THREAD

**Issue by denismaggior8** [haproxytech/helm-charts#93]
Both daemonset.yaml and deployment.yaml template files do not allow to configure metadata.annotations using values.

What we have:

```yaml
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
spec:
```

What we expect:

```yaml
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.deploymentAnnotations | indent 4 }}
  {{- end }}
spec:
```
