### ISSUE TITLE
HAProxy: allow configuring Environment variables

### ISSUE THREAD

**Issue by nafets227** [haproxytech/helm-charts#95]
I need to adopt to dynamic Ipv6 Prefixes on a DSL line.

Current solution (without helm) is to have a configmap with IPv6Prefix=ffff:ffff:ffff:ffff that is updated from a daemon running on Kubernetes node. This Configmap is imported into a environment variable and HAProxy file uses it to listen to the right addresses.

I'd like to use something similar with Helm, easiest way seems to allow a yaml snippet to be inserted into env: section of the HAProxy container

Helm values.yaml could contain something like this:
```
env:
- name: IPv6Prefix
  valueFrom:
    configMapKeyRef:
      name: nafets-ipv6
      key: IPv6Prefix
```
