### ISSUE TITLE
kubernetes-ingress  upgrade to 1.16.x nt working

### ISSUE THREAD

**Issue by benzman81** [haproxytech/helm-charts#97]
Hi,
we have a kubernetes-ingress helm chart running in v 1.15.4 in a bare metal kubernetes with metallb (dont know if this matters).
Now, when we upgrade to any 1.16.x version, then adding an ingress gets stuck initializing. Only reverting back to 1.15.4 will give us back a working ingress.
I could not find any changes needed for upgrade. Maybe you have an idea why this happens,

Our valus yaml is pretty simple:
```
controller:
  service:
    type: LoadBalancer
  resources:
    requests:
      memory: 192Mi
```
